development:
  host: localhost
  database: huzzah_development

test:
  host: localhost
  database: huzzah_test

# set these environment variables on your prod server
production:
  mongodb://javier:bolero@flame.mongohq.com:27097/huzzah
